
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfqgzpyweaqqgowvfrlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcWd6cHl3ZWFxcWdvd3ZmcmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzQ2NjIsImV4cCI6MjA1ODg1MDY2Mn0.Dd00e1iphMI6AEuwNFZTKjNgbhGa73ocvBiH95NmH_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
